/*
 * Shared client-side PDF renderer for esMetabolicLab results.
 *
 * Two entry points:
 *   - downloadStepTestReport({profile, sport, stages, bodyMass, sex, sessionId})
 *   - downloadPowerProfileReport({profile, sport, efforts, bodyMass, sex, altitude_m, sessionId})
 *
 * Both render to the same visual template — branded header, accent
 * dividers, a metrics table, the two on-screen charts captured via
 * Plotly.toImage, a training-zones page, and an "estimate" caveat
 * specific to the power-only path.
 *
 * Style intentionally tracks functions/report-renderer.js (the gait
 * analyzer's server-side PDF) so the two reports look like siblings.
 *
 * Requires:
 *   - window.jspdf.jsPDF        (loaded by the host page)
 *   - window.Plotly             (already loaded for on-screen charts)
 *   - On the host page, ids "chart-lactate" and "chart-substrate" must
 *     have been rendered (the on-screen draw calls handle this).
 */

import { generateZones } from './zones.js';
import { altitudeFactor } from '../lib/mader/constants.js';

const ACCENT      = [139, 124, 248];   // purple — esMetabolicLab brand
const ACCENT_ALT  = [0, 137, 123];     // teal — neutral header dividers
const BODY        = [26, 29, 39];      // near-black, easy on the eyes
const MUTED       = [120, 130, 150];   // mid-grey for secondary text
const SUBTLE      = [200, 205, 220];   // very light divider lines
const GOLD        = [200, 155, 30];    // for Fatmax accent
const GOOD        = [34, 160, 100];    // for MLSS accent
const PAGE_W      = 215.9;             // letter, mm
const PAGE_H      = 279.4;             // letter, mm
const MARGINS     = { top: 18, bottom: 18, left: 18, right: 18 };
const CONTENT_W   = PAGE_W - MARGINS.left - MARGINS.right;

function rgb(doc, fn, color) { doc[fn](color[0], color[1], color[2]); }
function setFill(doc, c)   { rgb(doc, 'setFillColor', c); }
function setText(doc, c)   { rgb(doc, 'setTextColor', c); }
function setDraw(doc, c)   { rgb(doc, 'setDrawColor', c); }

// jsPDF's built-in helvetica doesn't include subscripts, special arrows, or
// other extended glyphs — they render as garbage and inflate the measured
// width, so splitTextToSize breaks at the wrong points. Substitute before
// drawing or measuring anything.
function sanitize(s) {
  if (s == null) return '';
  return String(s)
    .replace(/₂/g, '2').replace(/₃/g, '3').replace(/₄/g, '4')
    .replace(/¹/g, '1').replace(/²/g, '2').replace(/³/g, '3')
    .replace(/[→↦⇒⇉➔]/g, 'to')
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/∞/g, 'inf')
    .replace(/≈/g, '~').replace(/≤/g, '<=').replace(/≥/g, '>=');
}
function dtext(doc, s, x, y, opts) { doc.text(sanitize(s), x, y, opts); }
function dsplit(doc, s, w) { return doc.splitTextToSize(sanitize(s), w); }

function ensure(doc, y, needed) {
  if (y + needed > PAGE_H - MARGINS.bottom) {
    drawFooter(doc);
    doc.addPage();
    drawFooter(doc);
    return MARGINS.top;
  }
  return y;
}

function drawFooter(doc) {
  setDraw(doc, SUBTLE);
  doc.setLineWidth(0.3);
  doc.line(MARGINS.left, PAGE_H - 12, PAGE_W - MARGINS.right, PAGE_H - 12);
  setText(doc, MUTED);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  dtext(doc, 'esMetabolicLab — Endurance Science Labs', MARGINS.left, PAGE_H - 8);
  var pageNum = doc.internal.getCurrentPageInfo().pageNumber;
  dtext(doc, 'Page ' + pageNum, PAGE_W - MARGINS.right, PAGE_H - 8, { align: 'right' });
}

function drawHeader(doc, toolName) {
  var y = MARGINS.top;
  // Logo box — purple square with "ESLabs"
  setFill(doc, ACCENT);
  doc.roundedRect(MARGINS.left, y, 16, 16, 3, 3, 'F');
  setText(doc, [255, 255, 255]);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  dtext(doc, 'ESLabs', MARGINS.left + 8, y + 10, { align: 'center' });

  // Brand + tool name
  setText(doc, BODY);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  dtext(doc, 'Endurance Science Labs', MARGINS.left + 20, y + 7);
  doc.setFontSize(12);
  setText(doc, ACCENT);
  dtext(doc, 'esMetabolicLab', MARGINS.left + 20, y + 14);
  y += 22;

  // Accent divider line
  setDraw(doc, ACCENT);
  doc.setLineWidth(0.6);
  doc.line(MARGINS.left, y, PAGE_W - MARGINS.right, y);
  y += 8;

  // Tool title (centered as a sub-headline)
  setText(doc, BODY);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  dtext(doc, toolName, MARGINS.left, y);
  y += 6;

  return y;
}

function drawMeta(doc, y, lines) {
  setText(doc, MUTED);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  for (var i = 0; i < lines.length; i++) {
    dtext(doc, lines[i], MARGINS.left, y);
    y += 5;
  }
  doc.setFontSize(8);
  dtext(doc, 'Generated by esMetabolicLab — endurancesciencelabs.com', MARGINS.left, y);
  y += 10;
  return y;
}

function drawSectionTitle(doc, y, text) {
  y = ensure(doc, y, 14);
  y += 2;
  setText(doc, ACCENT);
  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  dtext(doc, text, MARGINS.left, y);
  y += 9;
  return y;
}

// Title + chart + caption: page-break atomically so we don't strand a title
// at the bottom of a page with the chart on the next.
async function drawSectionWithChart(doc, y, title, chartId, caption, heightMm) {
  var needed = 14 + heightMm + 18; // title block + chart + caption + spacing
  if (y + needed > PAGE_H - MARGINS.bottom) {
    drawFooter(doc);
    doc.addPage();
    drawFooter(doc);
    y = MARGINS.top;
  }
  y = drawSectionTitle(doc, y, title);
  y = await drawChart(doc, y, chartId, caption, heightMm);
  return y;
}

// Render a metrics block as label / value / note rows with subtle separators.
function drawMetricsTable(doc, y, rows) {
  var labelX = MARGINS.left;
  var valueX = MARGINS.left + 28;
  var noteX  = MARGINS.left + 78;
  var noteW  = PAGE_W - MARGINS.right - noteX;
  var lineH  = 4;
  var pad    = 5;  // top + bottom padding per row

  for (var i = 0; i < rows.length; i++) {
    var r = rows[i];
    var noteLines = r.note
      ? dsplit(doc, r.note, noteW)  // measure BEFORE drawing — affects row height
      : [];
    var noteHeight = noteLines.length * lineH;
    var rowHeight = Math.max(9, noteHeight + pad);
    y = ensure(doc, y, rowHeight + 2);

    // Optional colored dot accent
    if (r.accent) {
      setFill(doc, r.accent);
      doc.circle(labelX - 2, y - 1.5, 1.3, 'F');
    }
    setText(doc, MUTED);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    dtext(doc, sanitize(r.label).toUpperCase(), labelX + 1, y);

    setText(doc, BODY);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    dtext(doc, String(r.value), valueX, y);

    if (noteLines.length) {
      setText(doc, MUTED);
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'normal');
      var ny = y;
      for (var j = 0; j < noteLines.length; j++) {
        doc.text(noteLines[j], noteX, ny);  // already sanitized via dsplit
        ny += lineH;
      }
    }

    y += rowHeight;
    setDraw(doc, SUBTLE);
    doc.setLineWidth(0.2);
    doc.line(labelX, y - 3, PAGE_W - MARGINS.right, y - 3);
  }
  return y + 4;
}

// Embed a Plotly chart by id, full content width, given height (mm).
async function drawChart(doc, y, chartId, captionText, heightMm) {
  if (!window.Plotly) return y;
  try {
    var imgUrl = await window.Plotly.toImage(chartId, {
      format: 'png', width: 1100, height: Math.round((heightMm / CONTENT_W) * 1100)
    });
    y = ensure(doc, y, heightMm + 16);
    doc.addImage(imgUrl, 'PNG', MARGINS.left, y, CONTENT_W, heightMm);
    y += heightMm + 4;
    if (captionText) {
      setText(doc, MUTED);
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'italic');
      var capLines = dsplit(doc, captionText, CONTENT_W);
      for (var i = 0; i < capLines.length; i++) {
        doc.text(capLines[i], MARGINS.left, y);
        y += 4;
      }
    }
    y += 8;  // breathing room before next section
  } catch (e) {
    console.warn('drawChart failed for ' + chartId + ':', e);
  }
  return y;
}

// Format helpers
function fmtPower(w) { return Math.round(w) + ' W'; }
function fmtPace(mps) {
  // mps → min:ss / mi
  if (!isFinite(mps) || mps <= 0) return '—';
  var secPerMi = 1609.344 / mps;
  var min = Math.floor(secPerMi / 60);
  var sec = Math.round(secPerMi - min * 60);
  if (sec === 60) { min++; sec = 0; }
  return min + ':' + (sec < 10 ? '0' : '') + sec + '/mi';
}
function fmtIntensity(sport, v) { return sport === 'cycling' ? fmtPower(v) : fmtPace(v); }
function fmtV(v) { return v.toFixed(1) + ' mL/min/kg'; }
function fmtPct(x) { return Math.round(x * 100) + '%'; }
function fmtLa(v) { return v.toFixed(1) + ' mmol/L'; }
function fmtG(v) { return v.toFixed(2) + ' g/min'; }
function fmtDate(d) { return d.toISOString().slice(0, 10); }
function fmtAltSpeed(v, alt_m, mlss_v) {
  if (!isFinite(v) || v <= 0) return '—';
  return fmtPace(v * altitudeFactor(alt_m, v / mlss_v));
}

function drawZoneTable(doc, y, title, rows, sport, opts) {
  opts = opts || {};
  y = ensure(doc, y, 16);

  setText(doc, BODY);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  dtext(doc, title, MARGINS.left, y);
  y += 5;

  var showAlt = sport === 'running' && opts.altitude_m && opts.altitude_m > 800 && opts.mlss_speed;
  var colZone = MARGINS.left;
  var colLabel = MARGINS.left + 14;
  var colRange = MARGINS.left + 78;
  var colAlt   = MARGINS.left + 138;
  var rowH = 6.5;

  // Header row
  setText(doc, MUTED);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  dtext(doc, 'ZONE', colZone, y);
  dtext(doc, 'LABEL', colLabel, y);
  dtext(doc, showAlt ? 'SEA LEVEL' : 'RANGE', colRange, y);
  if (showAlt) dtext(doc, 'AT ' + Math.round(opts.altitude_m) + ' M', colAlt, y);
  y += 2;
  setDraw(doc, ACCENT);
  doc.setLineWidth(0.3);
  doc.line(MARGINS.left, y, PAGE_W - MARGINS.right, y);
  y += 4;

  for (var i = 0; i < rows.length; i++) {
    var r = rows[i];
    y = ensure(doc, y, rowH);
    var lo = r.lo, hi = r.hi;
    var range = formatRange(sport, lo, hi);
    var altRange = showAlt ? formatAltRange(lo, hi, opts.altitude_m, opts.mlss_speed) : '';

    setText(doc, ACCENT);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    dtext(doc, 'Z' + r.zone, colZone, y);

    setText(doc, BODY);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    dtext(doc, r.label, colLabel, y);
    dtext(doc, range, colRange, y);
    if (showAlt) dtext(doc, altRange, colAlt, y);
    y += rowH;
  }
  return y + 4;
}

function formatRange(sport, lo, hi) {
  var loDef = !(lo === 0 || !isFinite(lo));
  var hiDef = isFinite(hi);
  if (sport === 'cycling') {
    if (!loDef && hiDef)  return 'up to ' + Math.round(hi) + ' W';
    if (loDef && !hiDef)  return Math.round(lo) + ' W and above';
    return Math.round(lo) + ' – ' + Math.round(hi) + ' W';
  }
  if (!loDef && hiDef)    return 'up to ' + fmtPace(hi);
  if (loDef && !hiDef)    return fmtPace(lo) + ' and faster';
  return fmtPace(lo) + ' – ' + fmtPace(hi);
}
function formatAltRange(lo, hi, alt_m, mlss_speed) {
  var loDef = !(lo === 0 || !isFinite(lo));
  var hiDef = isFinite(hi);
  if (!loDef && hiDef)    return 'up to ' + fmtAltSpeed(hi, alt_m, mlss_speed);
  if (loDef && !hiDef)    return fmtAltSpeed(lo, alt_m, mlss_speed) + ' and faster';
  return fmtAltSpeed(lo, alt_m, mlss_speed) + ' – ' + fmtAltSpeed(hi, alt_m, mlss_speed);
}

function drawDisclaimer(doc, y, extra) {
  y = ensure(doc, y, 24);
  setDraw(doc, SUBTLE);
  doc.setLineWidth(0.3);
  doc.line(MARGINS.left, y, PAGE_W - MARGINS.right, y);
  y += 5;
  setText(doc, MUTED);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'italic');
  var base = 'Not medical advice. esMetabolicLab is provided for educational purposes only and does not constitute a medical diagnosis or replace consultation with a qualified healthcare professional. Train within your means; consult a coach or physician before making significant training changes based on these results.';
  var text = extra ? (extra + ' ' + base) : base;
  var lines = dsplit(doc, text, CONTENT_W);
  for (var i = 0; i < lines.length; i++) {
    doc.text(lines[i], MARGINS.left, y);
    y += 4;
  }
  return y;
}

// Auto-sized tinted callout box. text is wrapped to width minus 16mm padding.
function drawCalloutBox(doc, y, title, body, accent) {
  var pad = 6;
  var titleH = 7;
  var bodyW = CONTENT_W - pad * 2;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  var bodyLines = dsplit(doc, body, bodyW);
  var bodyH = bodyLines.length * 4;
  var boxH = titleH + bodyH + pad;

  y = ensure(doc, y, boxH + 4);
  // Tinted background
  setFill(doc, [248, 246, 255]);
  doc.roundedRect(MARGINS.left, y, CONTENT_W, boxH, 2, 2, 'F');
  // Accent strip on the left
  setFill(doc, accent || ACCENT);
  doc.rect(MARGINS.left, y, 1.5, boxH, 'F');

  // Title
  setText(doc, BODY);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  dtext(doc, title, MARGINS.left + pad, y + 6);

  // Body
  setText(doc, [80, 80, 100]);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  var ty = y + titleH + 4;
  for (var i = 0; i < bodyLines.length; i++) {
    doc.text(bodyLines[i], MARGINS.left + pad, ty);
    ty += 4;
  }
  return y + boxH + 4;
}

// Auto-sized solid-color CTA box (used for the upgrade pitch).
function drawCtaBox(doc, y, title, body) {
  var pad = 7;
  var titleH = 9;
  var bodyW = CONTENT_W - pad * 2;
  doc.setFontSize(9.5);
  doc.setFont('helvetica', 'normal');
  var bodyLines = dsplit(doc, body, bodyW);
  var bodyH = bodyLines.length * 4;
  var boxH = titleH + bodyH + pad + 2;

  y = ensure(doc, y, boxH + 4);
  setFill(doc, ACCENT);
  doc.roundedRect(MARGINS.left, y, CONTENT_W, boxH, 3, 3, 'F');

  setText(doc, [255, 255, 255]);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  dtext(doc, title, MARGINS.left + pad, y + 8);

  doc.setFontSize(9.5);
  doc.setFont('helvetica', 'normal');
  var ty = y + titleH + 5;
  for (var i = 0; i < bodyLines.length; i++) {
    doc.text(bodyLines[i], MARGINS.left + pad, ty);
    ty += 4;
  }
  return y + boxH + 4;
}

// ── Public API ───────────────────────────────────────────────────

export async function downloadStepTestReport(params) {
  var p = params.profile;
  var sport = params.sport;
  var stages = params.stages || [];
  var bodyMass = params.bodyMass;
  var sex = params.sex;
  var sessionId = params.sessionId || '';

  var doc = new window.jspdf.jsPDF({ unit: 'mm', format: 'letter' });
  var y = drawHeader(doc, 'Lactate Step Test — Metabolic Profile');

  y = drawMeta(doc, y, [
    'Date: ' + fmtDate(new Date()) +
      '    Sport: ' + sport.charAt(0).toUpperCase() + sport.slice(1) +
      '    Sex: ' + (sex === 'M' ? 'Male' : 'Female') +
      '    Mass: ' + bodyMass + ' kg' +
      '    Stages: ' + stages.length
  ]);

  y = drawSectionTitle(doc, y, 'Your metabolic profile');
  y = drawMetricsTable(doc, y, [
    { label: 'VO₂max', value: fmtV(p.VO2max), accent: ACCENT,
      note: 'Aerobic ceiling — the most oxygen your body can use per minute.' },
    { label: 'VLamax', value: p.VLamax.toFixed(3) + ' mmol/L/s', accent: [255, 107, 53],
      note: 'How fast your body produces lactate at all-out sprint effort.' },
    { label: 'MLSS', value: fmtIntensity(sport, p.mlss.intensity), accent: GOOD,
      note: 'Maximum sustainable hard effort · ' + fmtPct(p.mlss.x) + ' VO₂max · ' + fmtLa(p.mlss.lactate) },
    { label: 'LT1', value: fmtIntensity(sport, p.lt1.intensity), accent: ACCENT,
      note: 'Top of your easy zone — where lactate first rises above baseline (' + fmtPct(p.lt1.x) + ' VO₂max).' },
    { label: 'Fatmax', value: fmtIntensity(sport, p.fatmax.intensity), accent: GOLD,
      note: 'Where fat-burning peaks · ' + fmtG(p.fatmax.fat_g_per_min) + ' at ' + fmtPct(p.fatmax.x) },
  ]);

  if (p.diagnostics && p.diagnostics.rmse !== undefined) {
    y = ensure(doc, y, 12);
    setText(doc, MUTED);
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'italic');
    var diagLine = 'Fit RMSE = ' + p.diagnostics.rmse.toFixed(2) + ' mmol/L';
    if (p.diagnostics.sensitivity) {
      var s = p.diagnostics.sensitivity;
      diagLine += '   ·   ±0.5 mmol/L lactate perturbation shifts VO₂max by ≤ ' +
                  s.max_VO2max_shift.toFixed(2) + ' mL/min/kg (' +
                  (s.max_VO2max_shift / s.base_VO2max * 100).toFixed(2) + '%).';
    }
    var dLines = dsplit(doc, diagLine, CONTENT_W);
    for (var di = 0; di < dLines.length; di++) {
      doc.text(dLines[di], MARGINS.left, y);
      y += 4;
    }
    y += 4;
  }

  y = await drawSectionWithChart(doc, y,
    'Lactate response across intensities',
    'chart-lactate',
    'Three curves: predicted blood lactate (purple), production rate (orange, right axis), max clearance (cyan dotted, right axis). MLSS sits where production crosses clearance.',
    78);

  y = await drawSectionWithChart(doc, y,
    'Fat vs carbohydrate burning',
    'chart-substrate',
    'Grams of fat and carbs burned per minute at each intensity. Fatmax (yellow dashed) is where fat-burning peaks.',
    78);

  // Page break before zones
  doc.addPage();
  drawFooter(doc);
  y = MARGINS.top;

  y = drawSectionTitle(doc, y, 'Training zones');
  setText(doc, MUTED);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  var introLines = dsplit(doc,
    'Zones below are anchored to your measured MLSS and LT1. Paste them straight into your training app.',
    CONTENT_W);
  for (var zi = 0; zi < introLines.length; zi++) {
    doc.text(introLines[zi], MARGINS.left, y);
    y += 4;
  }
  y += 3;

  var zones = generateZones(sport, { MLSS_intensity: p.mlss.intensity, LT1_intensity: p.lt1.intensity });
  var zoneOpts = { altitude_m: params.altitude_m || 0, mlss_speed: p.mlss.intensity };
  if (zones.coggan) y = drawZoneTable(doc, y, 'Coggan 7-zone (cycling)', zones.coggan, sport, zoneOpts);
  if (zones.friel)  y = drawZoneTable(doc, y, 'Friel 7-zone (running)',  zones.friel, sport, zoneOpts);
  if (zones.seiler) y = drawZoneTable(doc, y, 'Seiler 3-zone',           zones.seiler, sport, zoneOpts);

  if (p.diagnostics && Array.isArray(p.diagnostics.warnings) && p.diagnostics.warnings.length) {
    y = ensure(doc, y, 14);
    y = drawSectionTitle(doc, y, 'Notes from the engine');
    setText(doc, BODY);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    for (var wi = 0; wi < p.diagnostics.warnings.length; wi++) {
      var wLines = dsplit(doc, '- ' + p.diagnostics.warnings[wi], CONTENT_W);
      for (var wj = 0; wj < wLines.length; wj++) {
        y = ensure(doc, y, 5);
        doc.text(wLines[wj], MARGINS.left, y);
        y += 4;
      }
      y += 1;
    }
    y += 3;
  }

  y = drawDisclaimer(doc, y + 6);
  drawFooter(doc);

  var fn = 'esmetaboliclab-step-test-' + fmtDate(new Date()) + (sessionId ? ('-' + sessionId.slice(-6)) : '') + '.pdf';
  doc.save(fn);
}

export async function downloadPowerProfileReport(params) {
  var p = params.profile;
  var sport = params.sport;
  var bodyMass = params.bodyMass;
  var sex = params.sex;
  var altitude_m = params.altitude_m || 0;
  var sessionId = params.sessionId || '';

  var doc = new window.jspdf.jsPDF({ unit: 'mm', format: 'letter' });
  var y = drawHeader(doc, 'Power / Pace-only Profile — Estimate');

  y = drawMeta(doc, y, [
    'Date: ' + fmtDate(new Date()) +
      '    Sport: ' + sport.charAt(0).toUpperCase() + sport.slice(1) +
      '    Sex: ' + (sex === 'M' ? 'Male' : 'Female') +
      '    Mass: ' + bodyMass + ' kg' +
      (altitude_m ? ('    Altitude: ' + Math.round(altitude_m) + ' m') : '')
  ]);

  // Estimate caveat box (auto-sized)
  y = drawCalloutBox(doc, y,
    'This is an estimate, not a measurement.',
    'VLamax here is back-derived from your sprint power via an empirical regression. Real VLamax varies a lot at any given output. For lab-quality numbers, run a blood-lactate step test (or book an in-person session) at endurancesciencelabs.com/esmetaboliclab/pricing/.');

  y = drawSectionTitle(doc, y, 'Your estimated profile');
  y = drawMetricsTable(doc, y, [
    { label: 'VO₂max', value: fmtV(p.VO2max), accent: ACCENT,
      note: 'Estimated from your 6-minute max effort.' },
    { label: 'VLamax', value: p.VLamax.toFixed(3) + ' mmol/L/s', accent: [255, 107, 53],
      note: 'Back-derived from your 15-second sprint (least reliable).' },
    { label: 'MLSS', value: fmtIntensity(sport, p.mlss.intensity), accent: GOOD,
      note: 'Maximum sustainable effort · ' + fmtPct(p.mlss.x) + ' VO₂max · ' + fmtLa(p.mlss.lactate) },
    { label: 'LT1', value: fmtIntensity(sport, p.lt1.intensity), accent: ACCENT,
      note: 'Top of your easy zone (' + fmtPct(p.lt1.x) + ' VO₂max).' },
    { label: 'Fatmax', value: fmtIntensity(sport, p.fatmax.intensity), accent: GOLD,
      note: 'Where fat-burning peaks · ' + fmtG(p.fatmax.fat_g_per_min) + ' at ' + fmtPct(p.fatmax.x) },
  ]);

  y = await drawSectionWithChart(doc, y,
    'Lactate response across intensities',
    'chart-lactate',
    'Predicted blood lactate (purple), production rate (orange, right axis), max clearance (cyan dotted, right axis). MLSS sits where production crosses clearance.',
    78);

  y = await drawSectionWithChart(doc, y,
    'Fat vs carbohydrate burning',
    'chart-substrate',
    'Grams of fat and carbs burned per minute at each intensity. Fatmax (yellow dashed) is where fat-burning peaks.',
    78);

  // Page 2 — training zones
  doc.addPage();
  drawFooter(doc);
  y = MARGINS.top;

  y = drawSectionTitle(doc, y, 'Training zones (estimated)');
  setText(doc, MUTED);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  var introTxt = 'Zones below are anchored to your estimated MLSS and LT1. Treat them as a directional read, not a precision number — see the caveat above. A lactate-anchored test will sharpen these significantly.';
  if (altitude_m > 800) introTxt += ' Altitude-equivalent paces shown alongside sea level.';
  var introLines = dsplit(doc, introTxt, CONTENT_W);
  for (var zi = 0; zi < introLines.length; zi++) {
    doc.text(introLines[zi], MARGINS.left, y);
    y += 4;
  }
  y += 3;

  var zones = generateZones(sport, { MLSS_intensity: p.mlss.intensity, LT1_intensity: p.lt1.intensity });
  var zoneOpts = { altitude_m: altitude_m, mlss_speed: p.mlss.intensity };
  if (zones.coggan) y = drawZoneTable(doc, y, 'Coggan 7-zone (cycling)', zones.coggan, sport, zoneOpts);
  if (zones.friel)  y = drawZoneTable(doc, y, 'Friel 7-zone (running)',  zones.friel, sport, zoneOpts);
  if (zones.seiler) y = drawZoneTable(doc, y, 'Seiler 3-zone',           zones.seiler, sport, zoneOpts);

  // Upgrade CTA (auto-sized)
  y += 4;
  y = drawCtaBox(doc, y,
    'Want the real numbers?',
    'A lactate-anchored test pins VLamax, MLSS, and Fatmax directly. Run it yourself at home (upload access from $30) or book an in-person session with a coach ($145, Boulder / Denver area) at endurancesciencelabs.com/esmetaboliclab/pricing/.');

  y = drawDisclaimer(doc, y + 4);
  drawFooter(doc);

  var fn = 'esmetaboliclab-power-profile-' + fmtDate(new Date()) + (sessionId ? ('-' + sessionId.slice(-6)) : '') + '.pdf';
  doc.save(fn);
}
