/*
 * Shared client-side PDF renderer for esMetabolicLab results.
 *
 * Two entry points:
 *   - downloadStepTestReport({profile, sport, stages, bodyMass, sex, sessionId})
 *   - downloadPowerProfileReport({profile, sport, efforts, bodyMass, sex, altitude_m, sessionId})
 *
 * Both render to the same visual template — branded header, accent
 * dividers, a metrics table, the two on-screen charts captured via
 * Plotly.toImage, a training-zones page, and an "estimate" caveat
 * specific to the power-only path.
 *
 * Style intentionally tracks functions/report-renderer.js (the gait
 * analyzer's server-side PDF) so the two reports look like siblings.
 *
 * Requires:
 *   - window.jspdf.jsPDF        (loaded by the host page)
 *   - window.Plotly             (already loaded for on-screen charts)
 *   - On the host page, ids "chart-lactate" and "chart-substrate" must
 *     have been rendered (the on-screen draw calls handle this).
 */

import { generateZones } from './zones.js';
import { altitudeFactor } from '../lib/mader/constants.js';

const ACCENT      = [139, 124, 248];   // purple — esMetabolicLab brand
const ACCENT_ALT  = [0, 137, 123];     // teal — neutral header dividers
const BODY        = [26, 29, 39];      // near-black, easy on the eyes
const MUTED       = [120, 130, 150];   // mid-grey for secondary text
const SUBTLE      = [200, 205, 220];   // very light divider lines
const GOLD        = [200, 155, 30];    // for Fatmax accent
const GOOD        = [34, 160, 100];    // for MLSS accent
const PAGE_W      = 215.9;             // letter, mm
const PAGE_H      = 279.4;             // letter, mm
const MARGINS     = { top: 18, bottom: 18, left: 18, right: 18 };
const CONTENT_W   = PAGE_W - MARGINS.left - MARGINS.right;

function rgb(doc, fn, color) { doc[fn](color[0], color[1], color[2]); }
function setFill(doc, c)   { rgb(doc, 'setFillColor', c); }
function setText(doc, c)   { rgb(doc, 'setTextColor', c); }
function setDraw(doc, c)   { rgb(doc, 'setDrawColor', c); }

function ensure(doc, y, needed) {
  if (y + needed > PAGE_H - MARGINS.bottom) {
    drawFooter(doc);
    doc.addPage();
    drawFooter(doc);
    return MARGINS.top;
  }
  return y;
}

function drawFooter(doc) {
  setDraw(doc, SUBTLE);
  doc.setLineWidth(0.3);
  doc.line(MARGINS.left, PAGE_H - 12, PAGE_W - MARGINS.right, PAGE_H - 12);
  setText(doc, MUTED);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('esMetabolicLab — Endurance Science Labs', MARGINS.left, PAGE_H - 8);
  var pageNum = doc.internal.getCurrentPageInfo().pageNumber;
  doc.text('Page ' + pageNum, PAGE_W - MARGINS.right, PAGE_H - 8, { align: 'right' });
}

function drawHeader(doc, toolName) {
  var y = MARGINS.top;
  // Logo box — purple square with "ESLabs"
  setFill(doc, ACCENT);
  doc.roundedRect(MARGINS.left, y, 16, 16, 3, 3, 'F');
  setText(doc, [255, 255, 255]);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('ESLabs', MARGINS.left + 8, y + 10, { align: 'center' });

  // Brand + tool name
  setText(doc, BODY);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Endurance Science Labs', MARGINS.left + 20, y + 7);
  doc.setFontSize(12);
  setText(doc, ACCENT);
  doc.text('esMetabolicLab', MARGINS.left + 20, y + 14);
  y += 22;

  // Accent divider line
  setDraw(doc, ACCENT);
  doc.setLineWidth(0.6);
  doc.line(MARGINS.left, y, PAGE_W - MARGINS.right, y);
  y += 8;

  // Tool title (centered as a sub-headline)
  setText(doc, BODY);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(toolName, MARGINS.left, y);
  y += 6;

  return y;
}

function drawMeta(doc, y, lines) {
  setText(doc, MUTED);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  for (var i = 0; i < lines.length; i++) {
    doc.text(lines[i], MARGINS.left, y);
    y += 5;
  }
  doc.setFontSize(8);
  doc.text('Generated by esMetabolicLab — endurancesciencelabs.com', MARGINS.left, y);
  y += 10;
  return y;
}

function drawSectionTitle(doc, y, text) {
  y = ensure(doc, y, 12);
  setText(doc, ACCENT);
  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  doc.text(text, MARGINS.left, y);
  y += 7;
  return y;
}

function drawDivider(doc, y) {
  setDraw(doc, SUBTLE);
  doc.setLineWidth(0.3);
  doc.line(MARGINS.left, y, PAGE_W - MARGINS.right, y);
  return y + 5;
}

// Render a metrics block as label / value / note rows with subtle separators.
function drawMetricsTable(doc, y, rows) {
  var labelX = MARGINS.left;
  var valueX = MARGINS.left + 42;
  var noteX  = MARGINS.left + 100;
  var rowH   = 9;

  for (var i = 0; i < rows.length; i++) {
    var r = rows[i];
    y = ensure(doc, y, rowH);

    // Optional colored dot accent
    if (r.accent) {
      setFill(doc, r.accent);
      doc.circle(labelX - 2, y - 1.5, 1.3, 'F');
    }
    setText(doc, MUTED);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(r.label.toUpperCase(), labelX + 1, y);

    setText(doc, BODY);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text(String(r.value), valueX, y);

    if (r.note) {
      setText(doc, MUTED);
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'normal');
      var noteLines = doc.splitTextToSize(r.note, PAGE_W - MARGINS.right - noteX);
      for (var j = 0; j < noteLines.length; j++) {
        if (j === 0) doc.text(noteLines[j], noteX, y);
        else { y += 4; doc.text(noteLines[j], noteX, y); }
      }
    }

    y += rowH;
    setDraw(doc, SUBTLE);
    doc.setLineWidth(0.2);
    doc.line(labelX, y - 4, PAGE_W - MARGINS.right, y - 4);
  }
  return y + 2;
}

// Embed a Plotly chart by id, full content width, given height (mm).
async function drawChart(doc, y, chartId, captionText, heightMm) {
  if (!window.Plotly) return y;
  try {
    var imgUrl = await window.Plotly.toImage(chartId, {
      format: 'png', width: 1100, height: Math.round((heightMm / CONTENT_W) * 1100)
    });
    y = ensure(doc, y, heightMm + 12);
    doc.addImage(imgUrl, 'PNG', MARGINS.left, y, CONTENT_W, heightMm);
    y += heightMm + 2;
    if (captionText) {
      setText(doc, MUTED);
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'italic');
      var capLines = doc.splitTextToSize(captionText, CONTENT_W);
      for (var i = 0; i < capLines.length; i++) {
        doc.text(capLines[i], MARGINS.left, y + 3);
        y += 4;
      }
      y += 2;
    }
  } catch (e) {
    console.warn('drawChart failed for ' + chartId + ':', e);
  }
  return y;
}

// Format helpers
function fmtPower(w) { return Math.round(w) + ' W'; }
function fmtPace(mps) {
  // mps → min:ss / mi
  if (!isFinite(mps) || mps <= 0) return '—';
  var secPerMi = 1609.344 / mps;
  var min = Math.floor(secPerMi / 60);
  var sec = Math.round(secPerMi - min * 60);
  if (sec === 60) { min++; sec = 0; }
  return min + ':' + (sec < 10 ? '0' : '') + sec + '/mi';
}
function fmtIntensity(sport, v) { return sport === 'cycling' ? fmtPower(v) : fmtPace(v); }
function fmtV(v) { return v.toFixed(1) + ' mL/min/kg'; }
function fmtPct(x) { return Math.round(x * 100) + '%'; }
function fmtLa(v) { return v.toFixed(1) + ' mmol/L'; }
function fmtG(v) { return v.toFixed(2) + ' g/min'; }
function fmtDate(d) { return d.toISOString().slice(0, 10); }
function fmtAltSpeed(v, alt_m, mlss_v) {
  if (!isFinite(v) || v <= 0) return '—';
  return fmtPace(v * altitudeFactor(alt_m, v / mlss_v));
}

function drawZoneTable(doc, y, title, rows, sport, opts) {
  opts = opts || {};
  y = ensure(doc, y, 16);

  setText(doc, BODY);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGINS.left, y);
  y += 5;

  var showAlt = sport === 'running' && opts.altitude_m && opts.altitude_m > 800 && opts.mlss_speed;
  var colZone = MARGINS.left;
  var colLabel = MARGINS.left + 14;
  var colRange = MARGINS.left + 80;
  var colAlt   = MARGINS.left + 140;
  var rowH = 6.2;

  // Header row
  setText(doc, MUTED);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  doc.text('ZONE', colZone, y);
  doc.text('LABEL', colLabel, y);
  doc.text(showAlt ? 'SEA LEVEL' : 'RANGE', colRange, y);
  if (showAlt) doc.text('AT ' + Math.round(opts.altitude_m) + ' M', colAlt, y);
  y += 4;
  setDraw(doc, ACCENT);
  doc.setLineWidth(0.3);
  doc.line(MARGINS.left, y - 2, PAGE_W - MARGINS.right, y - 2);

  for (var i = 0; i < rows.length; i++) {
    var r = rows[i];
    y = ensure(doc, y, rowH);
    var lo = r.lo, hi = r.hi;
    var range = formatRange(sport, lo, hi);
    var altRange = showAlt ? formatAltRange(lo, hi, opts.altitude_m, opts.mlss_speed) : '';

    setText(doc, ACCENT);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('Z' + r.zone, colZone, y);

    setText(doc, BODY);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(r.label, colLabel, y);
    doc.text(range, colRange, y);
    if (showAlt) doc.text(altRange, colAlt, y);
    y += rowH;
  }
  return y + 4;
}

function formatRange(sport, lo, hi) {
  if (sport === 'cycling') {
    var a = (lo === 0 || !isFinite(lo)) ? '0 W' : Math.round(lo) + ' W';
    var b = isFinite(hi) ? Math.round(hi) + ' W' : '∞';
    return a + ' – ' + b;
  }
  var a2 = (lo === 0 || !isFinite(lo)) ? '—' : fmtPace(lo);
  var b2 = isFinite(hi) ? fmtPace(hi) : '—';
  return a2 + ' – ' + b2;
}
function formatAltRange(lo, hi, alt_m, mlss_speed) {
  var a = (lo === 0 || !isFinite(lo)) ? '—' : fmtAltSpeed(lo, alt_m, mlss_speed);
  var b = isFinite(hi) ? fmtAltSpeed(hi, alt_m, mlss_speed) : '—';
  return a + ' – ' + b;
}

function drawDisclaimer(doc, y, extra) {
  y = ensure(doc, y, 24);
  setDraw(doc, SUBTLE);
  doc.setLineWidth(0.3);
  doc.line(MARGINS.left, y, PAGE_W - MARGINS.right, y);
  y += 5;
  setText(doc, MUTED);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'italic');
  var base = 'Not medical advice. esMetabolicLab is provided for educational purposes only and does not constitute a medical diagnosis or replace consultation with a qualified healthcare professional. Train within your means; consult a coach or physician before making significant training changes based on these results.';
  var text = extra ? (extra + ' ' + base) : base;
  var lines = doc.splitTextToSize(text, CONTENT_W);
  for (var i = 0; i < lines.length; i++) {
    doc.text(lines[i], MARGINS.left, y);
    y += 4;
  }
  return y;
}

// ── Public API ───────────────────────────────────────────────────

export async function downloadStepTestReport(params) {
  var p = params.profile;
  var sport = params.sport;
  var stages = params.stages || [];
  var bodyMass = params.bodyMass;
  var sex = params.sex;
  var sessionId = params.sessionId || '';

  var doc = new window.jspdf.jsPDF({ unit: 'mm', format: 'letter' });
  var y = drawHeader(doc, 'Lactate Step Test — Metabolic Profile');

  y = drawMeta(doc, y, [
    'Date: ' + fmtDate(new Date()) +
      '    Sport: ' + sport.charAt(0).toUpperCase() + sport.slice(1) +
      '    Sex: ' + (sex === 'M' ? 'Male' : 'Female') +
      '    Mass: ' + bodyMass + ' kg' +
      '    Stages: ' + stages.length
  ]);

  y = drawSectionTitle(doc, y, 'Your metabolic profile');
  y = drawMetricsTable(doc, y, [
    { label: 'VO₂max', value: fmtV(p.VO2max), accent: ACCENT,
      note: 'Aerobic ceiling — the most oxygen your body can use per minute.' },
    { label: 'VLamax', value: p.VLamax.toFixed(3) + ' mmol/L/s', accent: [255, 107, 53],
      note: 'How fast your body produces lactate at all-out sprint effort.' },
    { label: 'MLSS', value: fmtIntensity(sport, p.mlss.intensity), accent: GOOD,
      note: 'Maximum sustainable hard effort · ' + fmtPct(p.mlss.x) + ' VO₂max · ' + fmtLa(p.mlss.lactate) },
    { label: 'LT1', value: fmtIntensity(sport, p.lt1.intensity), accent: ACCENT,
      note: 'Top of your easy zone — where lactate first rises above baseline (' + fmtPct(p.lt1.x) + ' VO₂max).' },
    { label: 'Fatmax', value: fmtIntensity(sport, p.fatmax.intensity), accent: GOLD,
      note: 'Where fat-burning peaks · ' + fmtG(p.fatmax.fat_g_per_min) + ' at ' + fmtPct(p.fatmax.x) },
  ]);

  if (p.diagnostics && p.diagnostics.rmse !== undefined) {
    y = ensure(doc, y, 12);
    setText(doc, MUTED);
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'italic');
    var diagLine = 'Fit RMSE = ' + p.diagnostics.rmse.toFixed(2) + ' mmol/L';
    if (p.diagnostics.sensitivity) {
      var s = p.diagnostics.sensitivity;
      diagLine += '   ·   ±0.5 mmol/L lactate perturbation shifts VO₂max by ≤ ' +
                  s.max_VO2max_shift.toFixed(2) + ' mL/min/kg (' +
                  (s.max_VO2max_shift / s.base_VO2max * 100).toFixed(2) + '%).';
    }
    var dLines = doc.splitTextToSize(diagLine, CONTENT_W);
    for (var di = 0; di < dLines.length; di++) {
      doc.text(dLines[di], MARGINS.left, y);
      y += 4;
    }
    y += 4;
  }

  y = drawSectionTitle(doc, y, 'Lactate response across intensities');
  y = await drawChart(doc, y, 'chart-lactate',
    'Three curves: predicted blood lactate (purple), production rate (orange, right axis), max clearance (cyan dotted, right axis). MLSS sits where production crosses clearance.',
    80);

  y = drawSectionTitle(doc, y, 'Fat vs carbohydrate burning');
  y = await drawChart(doc, y, 'chart-substrate',
    'Grams of fat and carbs burned per minute at each intensity. Fatmax (yellow dashed) is where fat-burning peaks.',
    80);

  // Page break before zones
  doc.addPage();
  drawFooter(doc);
  y = MARGINS.top;

  y = drawSectionTitle(doc, y, 'Training zones');
  setText(doc, MUTED);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  var introLines = doc.splitTextToSize(
    'Zones below are anchored to your measured MLSS and LT1. Paste them straight into your training app.',
    CONTENT_W);
  for (var zi = 0; zi < introLines.length; zi++) {
    doc.text(introLines[zi], MARGINS.left, y);
    y += 4;
  }
  y += 3;

  var zones = generateZones(sport, { MLSS_intensity: p.mlss.intensity, LT1_intensity: p.lt1.intensity });
  var zoneOpts = { altitude_m: params.altitude_m || 0, mlss_speed: p.mlss.intensity };
  if (zones.coggan) y = drawZoneTable(doc, y, 'Coggan 7-zone (cycling)', zones.coggan, sport, zoneOpts);
  if (zones.friel)  y = drawZoneTable(doc, y, 'Friel 7-zone (running)',  zones.friel, sport, zoneOpts);
  if (zones.seiler) y = drawZoneTable(doc, y, 'Seiler 3-zone',           zones.seiler, sport, zoneOpts);

  if (p.diagnostics && Array.isArray(p.diagnostics.warnings) && p.diagnostics.warnings.length) {
    y = ensure(doc, y, 14);
    y = drawSectionTitle(doc, y, 'Notes from the engine');
    setText(doc, BODY);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    for (var wi = 0; wi < p.diagnostics.warnings.length; wi++) {
      var wLines = doc.splitTextToSize('• ' + p.diagnostics.warnings[wi], CONTENT_W);
      for (var wj = 0; wj < wLines.length; wj++) {
        y = ensure(doc, y, 5);
        doc.text(wLines[wj], MARGINS.left, y);
        y += 4;
      }
      y += 1;
    }
    y += 3;
  }

  y = drawDisclaimer(doc, y + 6);
  drawFooter(doc);

  var fn = 'esmetaboliclab-step-test-' + fmtDate(new Date()) + (sessionId ? ('-' + sessionId.slice(-6)) : '') + '.pdf';
  doc.save(fn);
}

export async function downloadPowerProfileReport(params) {
  var p = params.profile;
  var sport = params.sport;
  var bodyMass = params.bodyMass;
  var sex = params.sex;
  var altitude_m = params.altitude_m || 0;
  var sessionId = params.sessionId || '';

  var doc = new window.jspdf.jsPDF({ unit: 'mm', format: 'letter' });
  var y = drawHeader(doc, 'Power / Pace-only Profile — Estimate');

  y = drawMeta(doc, y, [
    'Date: ' + fmtDate(new Date()) +
      '    Sport: ' + sport.charAt(0).toUpperCase() + sport.slice(1) +
      '    Sex: ' + (sex === 'M' ? 'Male' : 'Female') +
      '    Mass: ' + bodyMass + ' kg' +
      (altitude_m ? ('    Altitude: ' + Math.round(altitude_m) + ' m') : '')
  ]);

  // Estimate caveat box — purple-tinted accent strip
  y = ensure(doc, y, 22);
  setFill(doc, [248, 246, 255]);
  doc.roundedRect(MARGINS.left, y, CONTENT_W, 20, 2, 2, 'F');
  setFill(doc, ACCENT);
  doc.rect(MARGINS.left, y, 1.5, 20, 'F');
  setText(doc, BODY);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('This is an estimate, not a measurement.', MARGINS.left + 6, y + 6);
  setText(doc, [80, 80, 100]);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  var caveatLines = doc.splitTextToSize(
    'VLamax here is back-derived from your sprint power via an empirical regression. Real VLamax varies a lot at any given output. For lab-quality numbers, run a blood-lactate step test (or book an in-person session) at endurancesciencelabs.com/esmetaboliclab/pricing/.',
    CONTENT_W - 10);
  var cy = y + 11;
  for (var ci = 0; ci < caveatLines.length; ci++) {
    doc.text(caveatLines[ci], MARGINS.left + 6, cy);
    cy += 4;
  }
  y += 24;

  y = drawSectionTitle(doc, y, 'Your estimated profile');
  y = drawMetricsTable(doc, y, [
    { label: 'VO₂max', value: fmtV(p.VO2max), accent: ACCENT,
      note: 'Estimated from your 6-minute max effort.' },
    { label: 'VLamax', value: p.VLamax.toFixed(3) + ' mmol/L/s', accent: [255, 107, 53],
      note: 'Back-derived from your 15-second sprint (least reliable).' },
    { label: 'MLSS', value: fmtIntensity(sport, p.mlss.intensity), accent: GOOD,
      note: 'Maximum sustainable effort · ' + fmtPct(p.mlss.x) + ' VO₂max · ' + fmtLa(p.mlss.lactate) },
    { label: 'LT1', value: fmtIntensity(sport, p.lt1.intensity), accent: ACCENT,
      note: 'Top of your easy zone (' + fmtPct(p.lt1.x) + ' VO₂max).' },
    { label: 'Fatmax', value: fmtIntensity(sport, p.fatmax.intensity), accent: GOLD,
      note: 'Where fat-burning peaks · ' + fmtG(p.fatmax.fat_g_per_min) + ' at ' + fmtPct(p.fatmax.x) },
  ]);

  y = drawSectionTitle(doc, y, 'Lactate response across intensities');
  y = await drawChart(doc, y, 'chart-lactate',
    'Predicted blood lactate (purple), production rate (orange, right axis), max clearance (cyan dotted, right axis). MLSS sits where production crosses clearance.',
    78);

  y = drawSectionTitle(doc, y, 'Fat vs carbohydrate burning');
  y = await drawChart(doc, y, 'chart-substrate',
    'Grams of fat and carbs burned per minute at each intensity. Fatmax (yellow dashed) is where fat-burning peaks.',
    78);

  // Page 2 — training zones
  doc.addPage();
  drawFooter(doc);
  y = MARGINS.top;

  y = drawSectionTitle(doc, y, 'Training zones (estimated)');
  setText(doc, MUTED);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  var introTxt = 'Zones below are anchored to your estimated MLSS and LT1. Treat them as a directional read, not a precision number — see the caveat above. A lactate-anchored test will sharpen these significantly.';
  if (altitude_m > 800) introTxt += ' Altitude-equivalent paces shown alongside sea level.';
  var introLines = doc.splitTextToSize(introTxt, CONTENT_W);
  for (var zi = 0; zi < introLines.length; zi++) {
    doc.text(introLines[zi], MARGINS.left, y);
    y += 4;
  }
  y += 3;

  var zones = generateZones(sport, { MLSS_intensity: p.mlss.intensity, LT1_intensity: p.lt1.intensity });
  var zoneOpts = { altitude_m: altitude_m, mlss_speed: p.mlss.intensity };
  if (zones.coggan) y = drawZoneTable(doc, y, 'Coggan 7-zone (cycling)', zones.coggan, sport, zoneOpts);
  if (zones.friel)  y = drawZoneTable(doc, y, 'Friel 7-zone (running)',  zones.friel, sport, zoneOpts);
  if (zones.seiler) y = drawZoneTable(doc, y, 'Seiler 3-zone',           zones.seiler, sport, zoneOpts);

  // Upgrade CTA
  y = ensure(doc, y, 30);
  y += 4;
  setFill(doc, ACCENT);
  doc.roundedRect(MARGINS.left, y, CONTENT_W, 26, 3, 3, 'F');
  setText(doc, [255, 255, 255]);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Want the real numbers?', MARGINS.left + 8, y + 8);
  doc.setFontSize(9.5);
  doc.setFont('helvetica', 'normal');
  var ctaLines = doc.splitTextToSize(
    'A lactate-anchored test pins VLamax, MLSS, and Fatmax directly. Run it yourself at home (upload access from $30) or book an in-person session with a coach ($145, Boulder / Denver area) at endurancesciencelabs.com/esmetaboliclab/pricing/.',
    CONTENT_W - 16);
  var cyy = y + 14;
  for (var cli = 0; cli < ctaLines.length; cli++) {
    doc.text(ctaLines[cli], MARGINS.left + 8, cyy);
    cyy += 4;
  }
  y += 30;

  y = drawDisclaimer(doc, y + 4);
  drawFooter(doc);

  var fn = 'esmetaboliclab-power-profile-' + fmtDate(new Date()) + (sessionId ? ('-' + sessionId.slice(-6)) : '') + '.pdf';
  doc.save(fn);
}
